cask_args appdir: "/Applications"

# tap
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "appleboy/tap"

# brew
brew "awscli"
brew "azure-cli"
brew "bash-completion"
brew "ffmpeg"
brew "flyctl"
brew "git"
brew "git-lfs"
brew "git-secrets"
brew "gh"
brew "htop"
brew "jq"
brew "tree"
brew "watch"
brew "wget"
brew "mas"
brew "codegpt"
brew "volta"
brew "gibo"

# cask
cask "1password"
cask "audacity"
cask "balenaetcher"
cask "coteditor"
cask "discord"
cask "docker"
cask "dropbox"
cask "google-chrome"
cask "google-japanese-ime"
cask "elgato-control-center"
cask "elgato-stream-deck"
cask "firealpaca"
cask "iterm2"
cask "ngrok"
cask "sony-ps-remote-play"
cask "skitch"
cask "slack"
cask "tableau-public"
cask "the-unarchiver"
cask "vagrant"
#cask "virtualbox"
cask "visual-studio-code"
cask "voicepeak"
cask "zoom"
cask "deepl"
cask "microsoft-remote-desktop"
cask "multipass"

# mas
mas "kindle", id: 302584613
mas "line", id: 539883307
