name: 'Dotfiles'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  dotfiles:
    name: 'Dotfiles'
    runs-on: macos-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Tweak AWS CLI error with homebrew and macOS Image
      - name: tweak for AWS CLI in macOS image
        run: rm /usr/local/bin/aws && rm /usr/local/bin/aws_completer
          
      # Initialize and place dotfiles
      - name: Setup Dotfiles
        run: make
