name: 'Dotfiles'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  dotfiles:
    name: 'Dotfiles'
    runs-on: macos-14

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
          
      # Initialize and place dotfiles
      - name: Setup Dotfiles
        run: |
          MAS_APPS="$(cat .bin/.Brewfile | grep -v brew | grep -v "#" | grep mas | sed 's/^.*"\(.*\)".*$/\1/' | tr '\n' ' ')"
          export HOMEBREW_BUNDLE_MAS_SKIP="$MAS_APPS"
          export HOMEBREW_BUNDLE_BREW_SKIP="awscli azure-cli"
          export HOMEBREW_BUNDLE_CASK_SKIP="multipass tableau-public"
          make
